# Use phusion/baseimage as base image. To make your builds reproducible, make
# sure you lock down to a specific version, not to `latest`!
# See https://github.com/phusion/baseimage-docker/blob/master/Changelog.md for
# a list of version numbers.
FROM phusion/baseimage:latest

# Set correct environment variables.
ENV HOME /root

# Regenerate SSH host keys. baseimage-docker does not contain any, so you
# have to do that yourself. You may also comment out this instruction; the
# init system will auto-generate one during boot.
RUN /etc/my_init.d/00_regen_ssh_host_keys.sh

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]


##################################################################################################
## CUSTOMIZATION

# Shared volume with the codebase
VOLUME ["/root/biostar"]

# Install python, pip, git, postgresql client.
RUN apt-get update
RUN apt-get install -y python python-pip git postgresql-client-9.3 python-psycopg2

# Create a password file for PostgreSQL.
RUN echo "*:*:*:{{ postgresql_username }}:{{ postgresql_password }}" > /root/.pgpass
RUN chmod 0600 /root/.pgpass

# Expose SSH and webserver ports.
EXPOSE 8000 22

# Launch Django and run migrations when starting the container.
ENV BIOSTAR_HOME /root/biostar

# Add the webapp daemon: a Runit script executed on a `docker run`.
# Runit will keep the daemon up and running, restarting it when it crashes.
RUN mkdir /etc/service/webapp
RUN ln -s /root/biostar/run_webapp.sh /etc/service/webapp/run

# Install host's SSH public key.
RUN echo "{{ host_ssh_public_key.stdout }}" >> /root/.ssh/authorized_keys

## END CUSTOMIZATION
##################################################################################################


# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


###################################################################################################
## HOW TO USE IT
#
# Build:
#     docker build -t biostar/webapp .
# Run:
#     docker run -d --link postgresql:pg -p 80:8000 -p 2222:22 --volume=/mylocaldir:/root/biostar --name webapp biostar/webapp